[build]
  command = "pnpm run build"
  publish = ".next"
  functions = ".next/server"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--version"
  NODE_OPTIONS = "--experimental-specifier-resolution=node"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200