[build]
  command = "pnpm run build"
  publish = ".next"
  functions = ".next/server"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--version"
  NODE_OPTIONS = "--experimental-specifier-resolution=node"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle static assets
[[headers]]
  for = "/_static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle other static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle Next.js image optimization
[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["bot", "crawler", "spider", "external"], Country = ["us", "gb"]}