[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--version"
  # Enable ES modules support
  NODE_OPTIONS = "--experimental-specifier-resolution=node"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
